// Сценарии спроектированных ситуаций: чарт из .opencode/plans/evaluation
// 7 карт, HU, блайнды 100/200, стеки 10000.
// expect: массив допустимых действий. 'call' при toCall=0 = чек.
export const SCENARIOS = [
  {
    group: 'preflop',
    name: 'S-тир SB открыт, рейзов не было',
    hole: ['As', 'Ah', '2s', '3h', '4c', 'Ks', 'Qd'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 100,
    expect: ['raise'],
    note: 'S-тир: можно повышать, крупных рейзов не было'
  },
  {
    group: 'preflop',
    name: 'S-тир SB против джема',
    hole: ['As', 'Ah', '2s', '3h', '4c', 'Ks', 'Qd'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 10100,
    currentBet: 10000,
    actorCurrentBet: 100,
    oppCurrentBet: 10000,
    actions: [{ seat: 1, street: 'preflop', action: 'raise' }],
    oppHistory: { actions: 5, raises: 5, jams: 5 },
    expect: ['call'],
    note: 'монстр против олл-ина: играем'
  },
  {
    group: 'preflop',
    name: 'S-тир BB против рейза 600',
    hole: ['As', 'Ah', '2s', '3h', '4c', 'Ks', 'Qd'],
    street: 'preflop',
    actorIsDealer: false,
    pot: 700,
    currentBet: 600,
    actorCurrentBet: 200,
    oppCurrentBet: 600,
    actions: [{ seat: 0, street: 'preflop', action: 'raise' }],
    oppHistory: { actions: 10, raises: 9, jams: 2 },
    expect: ['call'],
    note: 'колл крупного рейза с монстром'
  },
  {
    group: 'preflop',
    name: 'A-тир SB лимп',
    hole: ['As', '2h', '3s', '5d', 'Ks', 'Kh', 'Qc'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 100,
    expect: ['call'],
    note: 'A-тир: колл (зависит от блайндов)'
  },
  {
    group: 'preflop',
    name: 'A-тир BB чек',
    hole: ['Ad', '2s', '3c', '5h', 'Kd', 'Kh', 'Qs'],
    street: 'preflop',
    actorIsDealer: false,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 200,
    expect: ['call'],
    note: 'A-тир на BB: бесплатный чек'
  },
  {
    group: 'preflop',
    name: 'B-тир SB',
    hole: ['As', '2h', '6c', '7d', 'Ks', 'Qs', 'Jh'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 100,
    expect: ['call', 'fold'],
    note: 'B-тир: колл зависит от ситуации'
  },
  {
    group: 'preflop',
    name: 'High-only KKQJT98 SB',
    hole: ['Ks', 'Kh', 'Qc', 'Jd', 'Ts', '9h', '8d'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 100,
    expect: ['raise', 'call'],
    note: 'A/B+ high-only HU: рейз или лимп'
  },
  {
    group: 'preflop',
    name: 'C-тир SB',
    hole: ['As', '2h', '8c', '9d', 'Ks', 'Qh', '6c'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 100,
    expect: ['call', 'fold'],
    note: 'C-тир: лимп или фолд'
  },
  {
    group: 'preflop',
    name: 'C-тир BB чек',
    hole: ['As', '2h', '8c', '9d', 'Ks', 'Qh', '6c'],
    street: 'preflop',
    actorIsDealer: false,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 200,
    expect: ['call'],
    note: 'C-тир на BB: чек бесплатно'
  },
  {
    group: 'preflop',
    name: 'D-тир SB фолд',
    hole: ['Qs', 'Jh', '9c', '7d', '6s', '4h', '3c'],
    street: 'preflop',
    actorIsDealer: true,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 100,
    expect: ['fold'],
    note: 'D-тир: всегда фолд'
  },
  {
    group: 'preflop',
    name: 'D-тир BB чек',
    hole: ['Qs', 'Jh', '9c', '7d', '6s', '4h', '3c'],
    street: 'preflop',
    actorIsDealer: false,
    pot: 300,
    currentBet: 200,
    actorCurrentBet: 200,
    expect: ['call'],
    note: 'D-тир на BB: чек (фолд нельзя)'
  },
  {
    group: 'preflop',
    name: 'D-тир BB против джема',
    hole: ['Qs', 'Jh', '9c', '7d', '6s', '4h', '3c'],
    street: 'preflop',
    actorIsDealer: false,
    pot: 10100,
    currentBet: 10000,
    actorCurrentBet: 200,
    oppCurrentBet: 10000,
    actions: [{ seat: 0, street: 'preflop', action: 'raise' }],
    oppHistory: { actions: 5, raises: 5, jams: 5 },
    expect: ['fold'],
    note: 'D-тир против олл-ина: фолд'
  },
  {
    group: 'river',
    name: 'Ривер натс-скоуп, последний ход, чекнули',
    hole: ['Ks', 'Kh', 'Ad', '4c', 'Qs', 'Jd', '8c'],
    board: ['Kd', '9h', '3s', '7c', '2h'],
    street: 'river',
    actorIsDealer: true,
    pot: 600,
    currentBet: 0,
    actions: [{ seat: 1, street: 'river', action: 'call' }],
    expect: ['raise'],
    note: 'натс + последний ход: ставка обязательна'
  },
  {
    group: 'river',
    name: 'Ривер натс-скоуп, ходить первым',
    hole: ['Ks', 'Kh', 'Ad', '4c', 'Qs', 'Jd', '8c'],
    board: ['Kd', '9h', '3s', '7c', '2h'],
    street: 'river',
    actorIsDealer: false,
    pot: 600,
    currentBet: 0,
    actions: [],
    expect: ['raise'],
    note: 'не последний: высокая вероятность ставки'
  },
  {
    group: 'river',
    name: 'Ривер натс против ставки',
    hole: ['Ks', 'Kh', 'Ad', '4c', 'Qs', 'Jd', '8c'],
    board: ['Kd', '9h', '3s', '7c', '2h'],
    street: 'river',
    actorIsDealer: true,
    pot: 1200,
    currentBet: 600,
    actorCurrentBet: 0,
    oppCurrentBet: 600,
    actions: [{ seat: 1, street: 'river', action: 'raise' }],
    expect: ['call', 'raise'],
    note: 'натс против ставки: колл или рейз'
  },
  {
    group: 'river',
    name: 'Ривер воздух, последний ход, чекнули',
    hole: ['Qs', 'Jh', '9c', '7d', '6s', '4h', '3c'],
    board: ['Kd', '9h', '3s', '7c', '2h'],
    street: 'river',
    actorIsDealer: true,
    pot: 600,
    currentBet: 0,
    actions: [{ seat: 1, street: 'river', action: 'call' }],
    expect: ['call'],
    note: 'воздух без ставки: чек'
  },
  {
    group: 'river',
    name: 'Ривер воздух против крупной ставки',
    hole: ['Qs', 'Jh', '9c', '7d', '6s', '4h', '3c'],
    board: ['Kd', '9h', '3s', '7c', '2h'],
    street: 'river',
    actorIsDealer: true,
    pot: 2600,
    currentBet: 2000,
    actorCurrentBet: 0,
    oppCurrentBet: 2000,
    actions: [{ seat: 1, street: 'river', action: 'raise' }],
    expect: ['fold'],
    note: 'воздух против ставки: фолд'
  },
  {
    group: 'flop',
    name: 'Флоп топ-пара + натс-лоу-дро, чекнули',
    hole: ['As', 'Ac', '2c', '4d', 'Ks', 'Qd', 'Jc'],
    board: ['Kd', '9h', '3s'],
    street: 'flop',
    actorIsDealer: true,
    pot: 600,
    currentBet: 0,
    actions: [{ seat: 1, street: 'flop', action: 'call' }],
    expect: ['raise', 'call'],
    note: 'сильный дро: ставка или чек'
  },
  {
    group: 'turn',
    name: 'Тёрн готовый натс-лоу + пара K против ставки',
    hole: ['As', 'Ac', '2c', '4d', 'Ks', 'Qd', 'Jc'],
    board: ['Kd', '9h', '3s', '7c'],
    street: 'turn',
    actorIsDealer: true,
    pot: 1200,
    currentBet: 600,
    actorCurrentBet: 0,
    oppCurrentBet: 600,
    actions: [{ seat: 1, street: 'turn', action: 'raise' }],
    expect: ['call', 'fold'],
    note: 'натс-лоу + пара: колл вероятнее'
  }
]
